#!/usr/bin/env ruby

require 'logger'
require File.expand_path('../lib/shell', __FILE__)

if ARGV.length < 2
  $stderr.puts "Usage: #$0 VDR_FILE MDES_VERSION"
  exit 1
end

logger = Logger.new($stderr)
shell = Shell.new(ARGV[0], ARGV[1], logger)

count = {}

shell.run do |node, _, name|
  if !count.has_key?(name)
    count[name] = 1
  else
    count[name] += 1
  end
end

count.keys.sort.each do |k|
  puts "#{k}\t#{count[k]}"
end
