#!/usr/bin/env ruby

require 'tempfile'

if ARGV.length < 2
  $stderr.puts "Usage: #$0 VDR_FILE MDES_VERSION"
  exit 1
end

Tempfile.open($0) do |f|
  puts "Generating diffstream to #{f.path}"

  vdr_diff_prep = File.expand_path('../vdr-diff-prep', __FILE__)

  cmd = "#{vdr_diff_prep} #{ARGV[0]} #{ARGV[1]} | sort > #{f.path} 2>/dev/null"
  system(cmd)

  cmd = "cat #{f.path} | cut -d':' -f1-2 | uniq | cut -d':' -f1 | uniq -c"
  system(cmd)
end
